### ISSUE TITLE
Great Job On This Project

### ISSUE THREAD

**Issue by clearsitedesigns** [omgitsraven/aframe-room-component#2]
This is great. I'm using this for building out a new rapid prototyping package that I use for teaching immersive design, UX, and work.

Is it possible to add custom materials to the walls (floor, ceiling)? That's the only thing I seemed to be running into an issue on.

**Comment by omgitsraven** [comment]
Thanks, glad I could be of help!

By 'custom material', do you mean something made with `registerShader`, or with the `registerComponent` workaround? I haven't tried either with this project yet—can you provide an example where it isn't working, so I can look into it? (Presently the material support works by looking at whatever's set in the `material` component, but I might be able to change how that works, to pick the material found on the 'mesh' object instead, maybe...)

**Comment by clearsitedesigns** [comment]
So with a plane primitive i could build an "asset-item" and then call that material via an ID - 
I could add my own textures (not just colors) to a plane. Using the asset item I could create a nice little separation in my code.

<a-asset-item id="wall" src="img/red-leather.jpg"></a-asset-item>

       <a-asset-item id="sky" src="img/brick-sky.jpg"></a-asset-item>
        <a-asset-item id="floor" src="img/floor-tiled.jpg"></a-asset-item>

<a-sky src="#sky"></a-sky>
It's entirely possible I might be calling this in the wrong way, or something has changed. 

I'll give more details i this doesn't make sense It's late:)

**Comment by omgitsraven** [comment]
What exactly is the issue that you're running into when you do that? It's working fine for me in the demonstration room: https://omgitsraven.github.io/aframe-room-component/examples/basic/ (Walk into the second room then turn around!)

**Comment by imaginethepoet** [comment]
It was an issue on my side. This is great! Thank you so much. I was running into an issue with my textures.
