### ISSUE TITLE
Have you thought about enable the room with physics like collision?

### ISSUE THREAD

**Issue by lilyzhng** [omgitsraven/aframe-room-component#3]
For now, the wall seems like be built up from 2D surface, which does not work to include the static body for collision.
<script src="https://cdn.rawgit.com/donmccurdy/aframe-physics-system/v2.1.0/dist/aframe-physics-system.js"></script>

<rw-wall static-body position="-3 0 0" material="color:#787"></rw-wall>

**Comment by omgitsraven** [comment]
I've thought about it, yes; I just haven't had a chance to yet. I'll try to find time soon!

**Comment by lilyzhng** [comment]
Thanks for the reply. Hope you could find a way to fix it soon.
