### ISSUE TITLE
Re Not working with Latest ver. of aframe js  (now: 1.2.0) - Any Future Version Upgrades?

### ISSUE THREAD

**Issue by quantumalchemy** [omgitsraven/aframe-room-component#5]
Great add-on / comp. to aframe js  but seems this project is dead no longer maintained .. can you confirm?
Thanks!

**Comment by omgitsraven** [comment]
oof, have A-Frame changes broken it *again*?  I assumed I was safe once A-Frame got to version 1.0...

I definitely am not really doing any A-Frame work these days, I'd like to fix it at some point but I can't really promise when, sorry.

**Comment by quantumalchemy** [comment]
Would be freakin' Great if you could  fix this thing maybe .. I love this thing! 
doesn't look to awful .. throwing error:
  in firefox:  Aframe 3
*** Uncaught TypeError: e.faces is undefined
        reexamineBuilding -->
aframe-room-component.js:116:26
- using latest aframe 1.2.0

**Comment by omgitsraven** [comment]
Good news, I've got a fix. It was actually a huge change; A-Frame upgraded its version of ThreeJS to a version that completely dropped support for the entire way I was making geometry... I've got it all re-written for the new system though. Just have to do the whole process of compiling it and pushing it live and so on, but I haven't done that in so long that I'm going to have to figure it out all over again, and I'm too tired tonight, hopefully I can get to it tomorrow.

**Comment by omgitsraven** [comment]
OK, it's done! (The NPM website isn't showing the update yet, but the command line is, so hopefully that's enough; it shouldn't be long before everything catches up either way.) I admit I haven't tested this very thoroughly yet (I've only run the example room), so there may be problems, particularly with UV generation; please let me know if it works!

**Comment by quantumalchemy** [comment]
Wow! Thanks So Much  Great Work!
after reloading: 2 small issues:
rw-floor  mixin="floor" ( ex image texture)  - not working worked in prev ver. works for rw-ceiling and mixin for walls ok
also rw-doorhole  have no depth (see side of walls in door  ) 
Thanks!

**Comment by omgitsraven** [comment]
Aha, I was afraid of that... OK, I'll take another look soon.

**Comment by arvind-iyer** [comment]
Should this be closed now?

**Comment by omgitsraven** [comment]
No, sorry -- between one thing and another I haven't gotten around to taking a closer look and figuring out why textures were breaking.

**Comment by omgitsraven** [comment]
Now fixed, thank you @oparamo !
