### ISSUE TITLE
Room component and A-Frame physics

### ISSUE THREAD

**Issue by mbofos01** [omgitsraven/aframe-room-component#8]
Is there any possible solution in order to make a-walls solid? I tried using the a-frame physics script but rooms and walls do not follow the same logic with other components. Eventually I set a a-plane behind each wall to block the user-camera? Could we make a custom component inherit from a primitive one?

**Comment by omgitsraven** [comment]
I've never really worked with collision in a-frame so I'm not sure, sorry!

**Comment by mbofos01** [comment]
Don't worry, thank you anyways. Great work!
